### PR TITLE
- Fixed uptime issue in macos

### PR DESCRIPTION
**Pull request by 1stdevfriend**
Signed-off-by: Kartikey Kushwah <kartikey@koders.in>

However, it's using awk and sed which comes default in both mac and linux
Try to please replace this via perl syntax cause it'll be third party dependent otherwise. 

image

### CODE REVIEW

**Comment by anhsirk0** [comment]
```perl
#!/usr/bin/env perl

my $boot = `sysctl -n kern.boottime`;
# my $boot = "{ sec = 1664182182, usec = 875003 }";
($boot) = $boot =~ /{ sec = (\d+)/;

my $now = time();
my $seconds = $now - $boot;

my $d = int($seconds / 60 / 60 / 24);
my $h = $seconds / 60 / 60 % 24;
my $m = $seconds / 60 % 60;
my $time = $d . "d, " . $h . "h, " . $m . "m";
$time =~ s/0., //g;
$time =~ s/^0., //g;

print $time . "\n";
```

Can you test out this script.

**Comment by 1stdevfriend** [comment]
image

**Comment by anhsirk0** [comment]
This is the way `fm6000` calculate uptime. You should pull new changes from master branch. and see if it works.

**Comment by 1stdevfriend** [comment]
Sure @anhsirk0

**Comment by 1stdevfriend** [comment]
Yes! It's working perfectly now. You can close this PR

**Comment by 1stdevfriend** [comment]
image

**Comment by anhsirk0** [comment]
You can use `-l` to specify length (in case your uptime grows even longer), I will try to add some way  automatically adjust length.

**Pull request closed without merging**
