### PR TITLE
Better install script

### PR DESCRIPTION
**Pull request by XDream8**

### CODE REVIEW

**Comment by anhsirk0** [comment]
I think we can skip checking for curl (its already installed mostly)
and also we used curl while downloading install script (curl install.sh | bash)
Is ~/.local/bin/ in $PATH ?? I am not sure about that  (if it is , we wont need sudo to move)

**Comment by XDream8** [comment]
> I think we can skip checking for curl (its already installed mostly)
> and also we used curl while downloading install script (curl install.sh | bash)
> Is ~/.local/bin/ in $PATH ?? I am not sure about that (if it is , we wont need sudo to move)

~/.local/bin is user script path its generally used. If that folder is not used it uses /usr/local/bin. Also it doesn't use sudo if ~/.local/bin is exist

**Comment by anhsirk0** [comment]
great

**Comment by anhsirk0** [comment]
Should I merge , or is there some changes you want to make?

**Comment by XDream8** [comment]
you can merge

**Pull request merged**
