### PR TITLE
binary installer

### PR DESCRIPTION
**Pull request by luis-07**
i added a binary and a installer for it

### CODE REVIEW

**Comment by anhsirk0** [comment]
Sorry I but don't understand what you are trying to do
You changed the shebang to #!/bin/
It wont work on BSD (It was #!/bin/perl when I first wrote the script, didnt work)
Binary didn't worked for me (EndeavourOS), how did you created the binary?
also I think there's no need for a Binary

**Comment by luis-07** [comment]
The changes with the shebang are for creating the binary I made the binary with the tool shc https://github.com/neurobin/shc
You can compile the binary yourself for your needs or in the normal installer is a option to download the tool and compile the binary

**Comment by anhsirk0** [comment]
Process of installing the binary is same as installing the script.
So why Binary ?
Is there a way you can create binary without changing the file
and 
Is there a way that we can both methods of installing?
Thanks

**Comment by luis-07** [comment]
Ok I can write a Python or bash script which creates the binary from the fm6000. It could change the shebang to #!/bin/perl and after creating the binary the script changes the shebang back. If you create the binary yourself does it work? 
i think if the installer creates the binary and the binary is not in the reop it would be better. 
try to change the shebang to #!/bin/perl on and create the binary with the command `shc -f fm6000.perl`. Shc will create tow files: fm6000.perl.x.c (the c file) and fm6000.perl.x (the binary) do this to test if the binary works on your system

**Comment by anhsirk0** [comment]
It will create a dependency (shc).
Why do we need a binary?
Sorry , if you feel opposed, I just dont want to complicate things.
If you want to make installation easy , i would sugest an AUR package for fm6000.
I cant make an AUR package right now (hands are full, also i dont know how to).
If you want the binary installer , I would suggest
Write a bash script change the shebang change it back and so on.
Send the PR for the installer script
Thanks

**Comment by XDream8** [comment]
Binary is not needed. its not a big file. its just a 12kb file that you are moving to $PATH

**Pull request closed without merging**
